In [1]:
import pandas as pd
import numpy as np

In [2]:
#Feed the data from the iea to create the dataframe
df_iea = pd.read_excel("http://www.iea.org/statistics/IEA_HeadlineEnergyData.xlsx", sheetname = "TimeSeries_1971-2017", skiprows = 1, index = False)
df_pwt = pd.read_excel("https://www.rug.nl/ggdc/docs/pwt90.xlsx", sheetname = "Data")

In [3]:
#Get rid of data we don't need so the dataframe for iea data with just the country, year, total primary energy, 
    #total final consumption, and total CO2 emissions.
df_iea = df_iea.drop(['NoCountry', 'NoProduct', 'NoFlow'], axis=1)
df_iea = df_iea[df_iea.Product == 'Total']
df_iea = df_iea[(df_iea.Flow =='Total primary energy supply (ktoe)') | (df_iea.Flow =='Total final consumption (ktoe)') | (df_iea.Flow=='Total CO2 emissions - Fuel Combustion (Mt of CO2)')]
df_iea = df_iea.sort_values(by = 'Country', ascending = True)
df_iea = df_iea.reset_index()
df_iea = df_iea.drop(['index'], axis = 1)

In [4]:
#Make new dataframe from pwt data with just country, year, and gdp. Coincidentally, the pwt data 
    #is already in matching country-year pairs
Country1 = df_pwt.country
Year1 = df_pwt.year
GDP = df_pwt.rgdpna
list_labels = ['Country', 'Year', 'GDP']
list_columns = [Country1, Year1, GDP]
zipped = list(zip(list_labels, list_columns))
data = dict(zipped)
dataframe_pwt = pd.DataFrame(data)

In [5]:
#Create lists that correspond to matching country-year pairs from df_iea.
df = df_iea.sort_values(by = 'Country', ascending = True)
Years2 = []
Countries2 = []
Total_primary_energy_supply = []
Total_final_consumption= []
Total_CO2_emissions_Fuel_Combustion = []

#This for loop iterates through df_iea, collects unique country-year pairs with the corresponding primary energy, 
    #final consumption, and CO2 emissions, and puts them into the correct lists.
for index, row in df_iea.iterrows():
    #This if statement checks to see if the country and year has already been added
    if df.loc[index, 'Country'] not in Countries2:
        for y in range(1971, 2018):
            Countries2.append(str(df_iea.loc[index, 'Country']))
            Years2.append(y)
    if(df_iea.loc[index, 'Flow'] == 'Total primary energy supply (ktoe)'):
        for y in range(1971, 2017):
            Total_primary_energy_supply.append(df.loc[index, y])
        if (y == '2017 Provisional') and (df.loc[index, y]):
            Total_primary_energy_supply.append(df.loc[index, y])
        else:
            Total_primary_energy_supply.append('NA')
    elif(df_iea.loc[index, 'Flow'] == 'Total final consumption (ktoe)'):
        for y in range(1971, 2017):
            Total_final_consumption.append(df.loc[index,y])
        if (y == '2017 Provisional') and (df.loc[index, y]):
            Total_final_consumption.append(df.loc[index,y])
        else:
            Total_final_consumption.append('NA')
    elif (df_iea.loc[index, 'Flow']== 'Total CO2 emissions - Fuel Combustion (Mt of CO2)'):
        for y in range(1971, 2017):
            Total_CO2_emissions_Fuel_Combustion.append(df.loc[index,y])
        if (y == '2017 Provisional') and (df.loc[index, y]):
            Total_CO2_emissions_Fuel_Combustion.append(df.loc[index,y])
        else:
            Total_CO2_emissions_Fuel_Combustion.append('NA')

In [6]:
#Creates a new dataframe so now the iea data is restructured with rows of matching country-year pairs
dataframe_iea = pd.DataFrame({'Country': Countries2, 'Year': Years2, 'Total CO2 emissions': Total_CO2_emissions_Fuel_Combustion, 'Total primary energy supply (ktoe)': Total_primary_energy_supply, 'Total final consumption (ktoe)': Total_final_consumption}, columns=['Country', 'Year', 'Total CO2 emissions', 'Total primary energy supply (ktoe)', 'Total final consumption (ktoe)'])
dataframe_iea.head(20)
#x = 0
#for index, row in df.iterrows():
 #   print('Country: ' + str(dataframe_iea.loc[index, 'Country']))
  #  print('Year: ' + str(dataframe_iea.iloc[index, 1]))
   # print('Total final consumption (ktoe): ' + str(dataframe_iea.iloc[index, 3]))
    #print('Total CO2 emissions: ' + str(dataframe_iea.iloc[index, 2]))
    #print('Total primary : '+ str(dataframe_iea.iloc[index, 4]))
    #x = x+1
#print(x)

,Country,Year,Total CO2 emissions,Total primary energy supply (ktoe),Total final consumption (ktoe)
0,Africa,1971,249.03,191939,159610
1,Africa,1972,263.84,198997,165939
2,Africa,1973,285.48,206867,172381
3,Africa,1974,299.17,214105,176332
4,Africa,1975,323.96,222573,183494
5,Africa,1976,352.25,232095,190876
6,Africa,1977,362.51,241318,197150
7,Africa,1978,352.67,252606,203471
8,Africa,1979,369.52,260007,209592
9,Africa,1980,397.69,275630,218278
10,Africa,1981,421.89,286233,226853
11,Africa,1982,431.53,307491,230260
12,Africa,1983,437.64,316647,234321
13,Africa,1984,453.28,329685,242050
14,Africa,1985,465.72,340312,248683
15,Africa,1986,471.07,352798,253273
16,Africa,1987,499.67,363751,261635
17,Africa,1988,510.43,372633,269682
18,Africa,1989,522.54,376116,278469
19,Africa,1990,529.11,391688,291792

In [7]:
#Puts both the IEA data and the PWT data together to create lists with matching country-year pairs with 
    #total primary energy, total final consumption, total CO2 emissions, and GDP
Cmplt_Countries = []
Cmplt_Years = []
Cmplt_GDP = []
Cmplt_TotalPrimaryEnergySupply = []
Cmplt_TotalFinalConsumption = []
Cmplt_TotalCO2EmissionsFuelCombustion = []
#Currently the PWT dataframe and the IEA dataframe have countries appearing repeatedly in order to create the country-year pairs.
    #There is also overlap in the countries that appear in PWT and IEA. This list accesses just the unique countries.
Total_Countries = list(set(list(set(Country1)) + list(set(Countries2))))
print('len of Total Countries: ' + str(len(Total_Countries)))
#This for loop iterates through the all of the unique countries. 
for indexa in range(0, len(Total_Countries)):
    country = Total_Countries[indexa]
    indexc = indexa
    #This for loop finds the index of the first instance of the country in the PWT dataframe.
    for x in range(0, len(dataframe_pwt.Country)):
        if dataframe_pwt.iloc[x, 0] == country:
            indexc = x
            break
    #This for loop iterates through all of the possible years with any data from pwt or iea. If data is available 
        #it adds the data to the correct, if it is not it adds NaN
    for y in range(1950, 2018):
        Cmplt_Countries.append(country)
        Cmplt_Years.append(y)
        #This if-else adds GDP if available, NaN if not. 
        if y in range(1950, 2015):
            if dataframe_pwt.iloc[indexc+(y-1950), 1]:
                Cmplt_GDP.append(dataframe_pwt.iloc[indexc+(y-1950), 1])
        else:
            Cmplt_GDP.append('NA')
        #This if-else adds total primary energy supply, total final consumption, and total CO2 emissions to the lists
            #if it is available, otherwise it adds 'NA'
        if (country in Countries2) & (y in range(1970, 2018)):
            #This for loop finds the index of the first instance of the country in the IEA dataframe
            index2c = list(dataframe_iea.Country).index(country)
            #index2y finds the index of the correct country-year pair. 
                #This is the index that we will use to find TPES, TFC, and TCO2E
            index2y = index2c+(y-1971)
            #print('index: ' + str(index2y))
            #The following if-else statement add TPES, TFC, and TCO2E if they are available, NaN if they are not
            if dataframe_iea.iloc[index2y, 2] != '..':
                Cmplt_TotalPrimaryEnergySupply.append(dataframe_iea.iloc[index2y, 2])
            else:
                Cmplt_TotalPrimaryEnergySupply.append('NA')
            if dataframe_iea.iloc[index2y, 3] != '..':
                Cmplt_TotalFinalConsumption.append(dataframe_iea.iloc[index2y, 3])
            else:
                Cmplt_TotalFinalConsumption.append('NA')
            if dataframe_iea.iloc[index2y, 4] != '..':
                Cmplt_TotalCO2EmissionsFuelCombustion.append(dataframe_iea.iloc[index2y, 4])
            else:
                Cmplt_TotalCO2EmissionsFuelCombustion.append('NA')
                
        else:
            Cmplt_TotalPrimaryEnergySupply.append('NA')
            Cmplt_TotalFinalConsumption.append('NA')
            Cmplt_TotalCO2EmissionsFuelCombustion.append('NA')

len of Total Countries: 193

In [9]:
#Create a dataframe with the complete lists
list_labels_final = ['Country', 'Year', 'GDP', 'Total primary energy supply', 'Total final consumption', 'Total CO2 emissions']
list_columns_final = [Cmplt_Countries, Cmplt_Years, Cmplt_GDP, Cmplt_TotalPrimaryEnergySupply, Cmplt_TotalFinalConsumption, Cmplt_TotalCO2EmissionsFuelCombustion]
zipped_final = list(zip(list_labels_final, list_columns_final))
data_final = dict(zipped_final)
dataframe_final = pd.DataFrame(data_final)
dataframe_final.sort_values(by = ['Country'])

Kyrgyzstan
OECD Total
Africa
Comoros
Mali
Costa Rica
Germany
Saint Lucia
Syrian Arab Republic
Belize
Ireland
China, Hong Kong SAR
Jordan
Ethiopia
Kuwait
Non-OECD Total
Guinea
Benin
Portugal
Turks and Caicos Islands
Barbados
Haiti
Honduras
Armenia
Australia
India
Indonesia
Uruguay
Finland
Niger
Iran (Islamic Republic of)
Sierra Leone
South Africa
Azerbaijan
Slovakia
Sudan (Former)
Swaziland
Pakistan
Bulgaria
Czech Republic
Bahamas
Guinea-Bissau
Georgia
St. Vincent and the Grenadines
Grenada
Iraq
Russian Federation
El Salvador
Cambodia
Myanmar
Equatorial Guinea
Bangladesh
Paraguay
Bahrain
Saudi Arabia
Japan
Hungary
Sweden
New Zealand
Oman
Maldives
Ukraine
TFYR of Macedonia
Rwanda
State of Palestine
Thailand
Sri Lanka
Togo
Aruba
Non-OECD Asia (including China)
Liberia
Cameroon
Saint Kitts and Nevis
Poland
Spain
United Kingdom
Uganda
Yemen
Kenya
Bolivia (Plurinational State of)
Nepal
Côte d'Ivoire
Kazakhstan
Croatia
Romania
Dominican Republic
Brazil
World
Slovak Republic
Burundi
Denmark
Austria
Gabon
Mongolia
Belarus
Italy
Singapore
Nicaragua
Malta
Tunisia
Zimbabwe
Cayman Islands
British Virgin Islands
Morocco
Nigeria
Uzbekistan
Non-OECD Europe and Eurasia
Suriname
Colombia
Estonia
Fiji
Malaysia
Senegal
Peru
Turkey
Cabo Verde
United States
Canada
Lebanon
Lithuania
Algeria
Non-OECD Americas
Dominica
Korea
Israel
Lao People's DR
Botswana
Latvia
Venezuela (Bolivarian Republic of)
People's Republic of China
Namibia
Gambia
Madagascar
Malawi
Mozambique
Slovenia
Chad
Guatemala
France
Ghana
Bosnia and Herzegovina
Albania
Taiwan
Middle East
Greece
Panama
Zambia
Central African Republic
Seychelles
D.R. of the Congo
Netherlands
Luxembourg
Egypt
Anguilla
Republic of Korea
Mauritania
Norway
Turkmenistan
Mauritius
China, Macao SAR
Lesotho
Jamaica
Philippines
Djibouti
Ecuador
Serbia
Belgium
Congo
Bermuda
Cyprus
Republic of Moldova
Angola
Brunei Darussalam
Sao Tome and Principe
Chile
Montenegro
Curaçao
Sint Maarten (Dutch part)
Bhutan
Viet Nam
Trinidad and Tobago
U.R. of Tanzania: Mainland
Burkina Faso
Tajikistan
United Arab Emirates
Montserrat
Iceland
Mexico
Antigua and Barbuda
Argentina
China
Switzerland
Qatar